trigger: none
pr:
  branches:
   include:
     - development
  paths:
    include:
      - devops/*
      - mlops/common/*
      - mlops/diabetes/*
      - src/diabetes/*
      - model/diabetes/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_infra_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "pr"
 - name: model_type
   displayName: "model type"
   default: "diabetes"

stages:
  - template: ../templates/variables_template.yml
    parameters:
      env_name: ${{parameters.env_name}}
      model_type: ${{parameters.model_type}}
  - template: ../platform_pr_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}