pr: none
trigger:
  branches:
   include:
     - development
  paths:
    include:
      - devops/*
      - mlops/common/*
      - mlops/london_taxi/*
      - src/london_src/*
      - model/london_taxi/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment (ie pr or dev)"
 - name: model_type
   displayName: "model type (ie london_taxi or nyc_taxi)"
 - name: is_batch_deployment
   default: 'None'
   displayName: "****Only for dev***: None when env_name=pr, OR True for batch endpoint and False for real-time endpoint"

stages:
  - template: templates/variables_template.yml
    parameters:
      env_name: ${{parameters.env_name}}
      model_type: ${{parameters.model_type}}


  - ${{ if eq(parameters.env_name, 'pr') }}:
    - template: platform_pr_dev_pipeline.yml
      parameters:
        exec_environment: ${{ parameters.env_name }}
        model_type: ${{ parameters.model_type }}

  - ${{ if eq(parameters.env_name, 'dev') }}:
    - template: platform_ci_dev_pipeline.yml
      parameters:
        exec_environment: ${{ parameters.env_name }}
        model_type: ${{ parameters.model_type }}
        is_batch_deployment: ${{ parameters.is_batch_deployment }}
