pool:
  name: Azure Pipelines
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformTaskV4@4
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/private_workspace'
    backendServiceArm: 'infra_service_connection'
    backendAzureRmResourceGroupName: 'mlopsv2infra'
    backendAzureRmStorageAccountName: tfstoracct2 
    backendAzureRmContainerName: terraform
    backendAzureRmKey: mlops.tfstate

- task: TerraformTaskV4@4
  displayName: 'Terraform Validate'
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/private_workspace'



- task: TerraformTaskV4@4
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/private_workspace'
    allowTelemetryCollection: true
    environmentServiceNameAzureRM: 'infra_service_connection'
    commandOptions: '-out=tfplan'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/private_workspace'
    environmentServiceNameAzureRM: 'infra_service_connection'
    commandOptions: '-auto-approve -input=false  tfplan'