trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
    
    wget -O- https://apt.releases.hashicorp.com/gpg |gpg --dearmor | \
    sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

    gpg --no-default-keyring \
    --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    --fingerprint

    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    sudo tee /etc/apt/sources.list.d/hashicorp.list

    sudo apt update
    sudo apt-get install terraform

    terraform version
  displayName: 'Installing Terrafrom'

- script: |
    sudo apt-get update
    sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
    
    sudo mkdir -p /etc/apt/keyrings
    curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor |
        sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
    sudo chmod go+r /etc/apt/keyrings/microsoft.gpg

    AZ_REPO=$(lsb_release -cs)
    echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
        sudo tee /etc/apt/sources.list.d/azure-cli.list

    sudo apt-get update
    sudo apt-get install azure-cli
    
    az upgrade
    az config set auto-upgrade.enable=yes
    
  displayName: 'Azure CLI Updated and Ubuntu'

- script: |
    $tenantid="16b3c013-d300-468d-ac64-7eda0820b6d3"
    $subscriptionid="310ab569-9762-484e-8ce9-a650803297ea"

    echo $tenantid
    echo $subscriptionid
    
    az login --tenant $tenantid
    az account set --name $subscriptionid
    cd infra/terraform/public_workspace/
    
    terraform init
    terraform plan
    terraform apply --auto-plan
    echo "Resources have been built. Give it a minute to check through the portal."
  displayName: 'Running Terraform files'