steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'infra_service_connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo "test"'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    allowTelemetryCollection: true
  

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    allowTelemetryCollection: true