variables:
- group: tf_public_vg

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'infra_service_connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo "test"'
  displayName: Service Connection

- task: AzureCLI@2
  inputs:
    azureSubscription: 'infra_service_connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    inlineScript: 'ls'
  displayName: Current Dictory

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
  displayName: Terraform Init
  
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    allowTelemetryCollection: true
  displayName: Terraform Validate
  
#- task: TerraformCLI@0
#  inputs:
#    command: 'plan'
#    workingDirectory: '$(System.DefaultWorkingDirectory)/intra/terraform/public_workspace'
#    environmentServiceName: 'infra_service_connection'
#    providerAzureRmSubscriptionId: '310ab569-9762-484e-8ce9-a650803297ea'
#    runAzLogin: true
#    commandOptions: '-var "basename=$(basename)" -var "location=$(location)" -var "rg_name=$(rg_name)" -var "subscription_id=$(subscription_id)" -var "tenant_id=$(tenant_id)"  -var "version_num=$(version_num)"'
#    allowTelemetryCollection: true
#  displayName: Terrafor Plan
    
  
#- task: TerraformCLI@0
#  inputs:
#    command: 'apply'
#    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
#    allowTelemetryCollection: true