variables:
- group: tf_public_vg

steps:

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    backendServiceArm: 'infra_service_connection'
    backendAzureRmResourceGroupName: 'rg-MLOps-V2'
    backendAzureRmStorageAccountName: tfstoragev2 
    backendAzureRmContainerName: terraform
    backendAzureRmKey: mlops.tfstate
  displayName: Terraform Init
  
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    allowTelemetryCollection: true
  displayName: Terraform Validate

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/intra/terraform/public_workspace'
    environmentServiceName: 'infra_service_connection'
    runAzLogin: true
    commandOptions: "-out=tfplan"
    allowTelemetryCollection: true
  displayName: Terrafor Plan
    
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    environmentServiceName: 'infra_service_connection'
    commandOptions: '-auto-approve -input=false tfplan'
    allowTelemetryCollection: true
  displayName: Terraform Apply