steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'infra_service_connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo "test"'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/public_workspace'
    allowTelemetryCollection: true