name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - scikit-learn==1.2.0
    - mlflow==2.4.1
    - azureml-mlflow==1.52.0
    - mldesigner==0.1.0b4
    - azure-ai-ml==1.8.0
    - azure-identity==1.11.0
    - azure-keyvault-secrets==4.6.0
    - azureml-inference-server-http
    - xgboost==1.7.6
