name: ModelFactory-Bicep-Deployment
on:
  workflow_dispatch:
env:
  APPINSIGHTS_NAME: ${{ vars.APPINSIGHTS_NAME }}
  AZURE_RM_SVC_CONNECTION: ${{ vars.AZURE_RM_SVC_CONNECTION }}
  CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
  KEYVAULT_NAME: ${{ vars.KEYVAULT_NAME }}
  LOCATION: ${{ vars.LOCATION }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  STORAGE_ACCT_NAME: ${{ vars.STORAGE_ACCT_NAME }}
  WORKSPACE_NAME: ${{ vars.WORKSPACE_NAME }}
jobs:
  run-infra-provision:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Display parameters
        run: |
          echo 'See the contents of parameters passed in'
          echo $APPINSIGHTS_NAME
          echo $AZURE_RM_SVC_CONNECTION
          echo $CONTAINER_REGISTRY_NAME
          echo $KEYVAULT_NAME
          echo $LOCATION
          echo $RESOURCE_GROUP_NAME
          echo $STORAGE_ACCT_NAME
          echo $WORKSPACE_NAME
          echo ${{ github.workspace }}
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          
          
      - name: Provision AzureML Infrastructure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az --version
            az deployment sub create --location=$LOCATION \
            --template-file '${{ github.workspace }}/infra/bicep/public_workspace/main.bicep' \
            --parameters resourceGroupName=$RESOURCE_GROUP_NAME location=$LOCATION \
            storageAccount=$STORAGE_ACCT_NAME \
            keyVaultName=$KEYVAULT_NAME \
            appInsightsName=$APPINSIGHTS_NAME \
            containerRegistryName=$CONTAINER_REGISTRY_NAME \
            amlWorkspaceName=$WORKSPACE_NAME
