name: Platform CI Workflow
on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      model_type:
        type: string
        description: "type of model to execute"
        required: true
    secrets:
      subscription_id:
        description: "the subscription ID hosting the AML instance."
        required: true
      resource_group_name:
        description: "the resource group name hosting the AML instance."
        required: true
      workspace_name:
        description: "the workspace name hosting the AML instance."
        required: true
      azure_credentials:
        description: "the credentials to use to authenticate with Azure."
        required: true
jobs:
  execute-training-job:
    name: Execute training job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
      - name: Execute MLOps Standard Pipeline
        uses: ./.github/actions/execute_shell_code
        env: 
            SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
            RESOURCE_GROUP_NAME: ${{ secrets.resource_group_name }}
            WORKSPACE_NAME: ${{ secrets.workspace_name }}
            BUILD_BUILDID: ${{ github.run_id }}
        with:
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.${{ inputs.model_type }}.src.mlops_pipeline \
                  --build_environment ${{ inputs.exec_environment }} \
                  --wait_for_completion True \
                  --output_file run_id.txt
      - name: Read Run ID
        shell: bash
        run: |
          readarray arr <"run_id.txt"
          run_name=${arr[0]}
          echo $run_name
          echo "RUN_NAME=${run_name}"  >> "$GITHUB_ENV"

  deploy-online:
    name: Deploy_Online
    runs-on: ubuntu-latest
    needs: [execute-training-job]
    env:
      SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
      RESOURCE_GROUP_NAME: ${{ secrets.resource_group_name }}
      WORKSPACE_NAME: ${{ secrets.workspace_name }}
      BUILD_BUILDID: ${{ github.run_id }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
      - name: Provision azureml online endpoint
        uses: ./.github/actions/execute_shell_code
        with: 
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.common.deployment.provision_online_endpoint \
                  --model_type ${{ inputs.model_type }} \
                  --environment_name ${{ inputs.exec_environment }} \
                  --run_id ${{ github.run_id }} 
      - name: Provision azureml deployment
        uses: ./.github/actions/execute_shell_code
        with: 
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.common.deployment.provision_online_deployment \
                  --model_type ${{ inputs.model_type }} \
                  --environment_name ${{ inputs.exec_environment }} \
                  --run_id ${{ github.run_id }}
      - name: Test azureml real endpoint
        uses: ./.github/actions/execute_shell_code
        with: 
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.common.deployment.run_test_model_on_aml \
                    --environment_name ${{ inputs.exec_environment }} \
                    --model_type ${{ inputs.model_type }}

  deploy-batch:
    name: Deploy_Batch
    runs-on: ubuntu-latest
    needs: [execute-training-job]
    env:
        SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
        RESOURCE_GROUP_NAME: ${{ secrets.resource_group_name }}
        WORKSPACE_NAME: ${{ secrets.workspace_name }}
        BUILD_BUILDID: ${{ github.run_id }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
      - name: Provision azureml online endpoint
        uses: ./.github/actions/execute_shell_code
        with: 
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.common.deployment.provision_batch_endpoint \
                  --run_id ${{ github.run_id }} \
                  --environment_name ${{ inputs.exec_environment }} \
                  --model_type ${{ inputs.model_type }}
      - name: Provision azureml deployment
        uses: ./.github/actions/execute_shell_code
        with: 
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.common.deployment.provision_batch_deployment \
                  --run_id ${{ github.run_id }} \
                  --environment_name ${{ inputs.exec_environment }} \
                  --model_type ${{ inputs.model_type }}
      - name: Test azureml batch endpoint
        uses: ./.github/actions/execute_shell_code
        with: 
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.common.deployment.run_test_batch_deployment \
                  --environment_name ${{ inputs.exec_environment }} \
                  --model_type ${{ inputs.model_type }}

  change_model_tag:
    name: Apply Production Tag
    runs-on: ubuntu-latest
    needs: [execute-training-job]
    env:
      SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
      RESOURCE_GROUP_NAME: ${{ secrets.resource_group_name }}
      WORKSPACE_NAME: ${{ secrets.workspace_name }}
      BUILD_BUILDID: ${{ github.run_id }}
    steps:
        - name: Checkout Actions
          uses: actions/checkout@v1
        - name: Configure Azure ML Agent
          uses: ./.github/actions/configure_azureml_agent
        - name: Provision azureml online endpoint
          uses: ./.github/actions/execute_shell_code
          with:
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.common.deployment.approve_model \
                  --model_type ${{ inputs.model_type }}