name: Sanity CI for Node.js Project

on:
  workflow_dispatch: 
  push:
    branches:
      [development/cicdautomation]

jobs:
  build:
    runs-on: self-hosted
    environment: fiduciary
    name: Build and Test
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate via AZCLI
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}
          az group show --name modelfactory1b
          # You can write your Azure CLI inline scripts here.