name: Register Datasets

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9"

jobs:
  run-registration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
      - name: Execute Dataset Registration
        uses: ./.github/actions/execute_shell_code
        env: 
            SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
            RESOURCE_GROUP_NAME: ${{ secrets.resource_group_name }}
            WORKSPACE_NAME: ${{ secrets.workspace_name }}
        with:
            azure_credentials: ${{ secrets.azure_credentials }}
            script_parameter: |
                python -m mlops.common.register_data_asset \
                    --data_config_path config/data_config.json
