pr: none
trigger: none
pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg

stages:
  - template: ../../templates/variables_template_infra.yml
  - template: ../../platform_infra_terraform_pipeline.yml
    parameters:
      azureMgrConnection: $(AZURE_RM_SVC_CONNECTION)
      resourceGroup: $(RESOURCE_GROUP_NAME)
      keyVaultName: $(KEYVAULT_NAME)
      amlWorkspaceName: $(WORKSPACE_NAME)
      clusterName: $(CLUSTER_NAME)
      batchClusterName: $(BATCH_CLUSTER_NAME)
